### ISSUE TITLE
Adding Czech language

### ISSUE THREAD

**Issue by MasterVotr** [SACompanion/translations#18]
Helo, my name is Jacob and I would like to translate Survive ARK Companion to my language - Czech language

**Comment by LandDragoon** [comment]
Hey, I've created a language file that you can use for this. It can be found here: https://github.com/SACompanion/translations/blob/master/translations_cz.txt

Good luck with the translations and thanks a lot for helping with it! :)

**Comment by LandDragoon** [comment]
I've added your changes to the original file. It should also have fixed your issue with one of the sentences around line 145 :) 
Edit: and also around line 177
