### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Azorian** [SACompanion/translations#19]
It is a wrong Translation by the Taming calculator.

At the Category Time ("Timer") is written "Verhungert in XXm XXs" and this Means in German "It died by hunger in XXm XXs". The right word would be "Ausgehungert in" this means he has enough hunger. Respectively he has hunger.

Sorry, for my bad english ^^ I hope I could explain it in some way.

greetings Azo

**Comment by LandDragoon** [comment]
So you mean it would be better to have "Ausgehungert in XXm XXs" instead of "Verhungert in XXm XXs", right? I'll change it in the next version of the app. Thanks for letting me know! :)
