### ISSUE TITLE
Add italian lenguage

### ISSUE THREAD

**Issue by psykoboy** [SACompanion/translations#28]
I help you to traslate

**Comment by LandDragoon** [comment]
You can find the Italian file here: https://github.com/SACompanion/translations/blob/master/translations_it.txt

**Comment by VadaViaElCuu** [comment]
Excuse me, I am pretty noob about those stuffs, I would be glad to help about this subject, but I have no idea about how to modify the file. :C

**Comment by LandDragoon** [comment]
@VadaViaElCuu you can go to a file (e.g. the Italian Language file: https://github.com/SACompanion/translations/blob/master/translations_it.txt ) and press the pencil icon in the top right corner. Then you'll be able to edit the file. 

After you've made some changes, save the file and let me know about it so I can combine it with the other translations :)

If you don't want to use GitHub, send me a mail so I can send you the translation file.
